#fly.toml file generated for restoremarko on 2024-09-17T15:40:58+07:00

app = 'restoremarko'
primary_region = 'waw'

[build]
  image = 'marko3107/restoremarko:latest'

[env]
  ASPNETCORE_URLS = "http://+:8080"
  StripeSettings__PublishableKey="pk_test_51PxpogKTI6usqA8ymWRKCGyovMBJEfAP0QiHDXHXwC7N16y34GNlcxqTMRdnv7r3qKfMPXB6ej9lxk9ZwLYTXTb100oQt07vyC"

[experimental]
  allowed_public_ports=[]
  auto_rollback = true

[[services]]
  http_checks = []
  protocol = 'tcp'
  internal_port = 8080
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"

[[vm]]
  size = 'shared-cpu-1x'
